Repository awslabs/fhir-works-on-aws-authz-smart, pull requests merged in 2021-09, with the labels that each got.

#61 chore: normalize all the line endings
  .github/PULL_REQUEST_TEMPLATE.md
  .github/no-response.yaml
  .npmignore
  .npmrc
  .prettierrc.js
  THIRD-PARTY
  src/index.ts
  src/regExpressions.test.ts
  src/smartConfig.ts
  src/smartHandler.test.ts
Labels: size/xl

#62 chore: bump axios version
  package.json
  yarn.lock
Labels: size/s

#64 fix: scope checking for getting status on an export
  src/smartScopeHelper.test.ts
  src/smartScopeHelper.ts
Labels: size/m

#65 chore(release): 2.2.3
  CHANGELOG.md
  package.json
Labels: documentation, size/xs

#63 fix: remove filtered responses from total count
  src/smartHandler.test.ts
  src/smartHandler.ts
Labels: size/s

#60 feat: update system export to only allow system scope by default
  src/smartHandler.test.ts
  src/smartHandler.ts
  src/smartScopeHelper.test.ts
  src/smartScopeHelper.ts
Labels: size/m

#66 chore(release): 3.0.0
  CHANGELOG.md
  package.json
Labels: size/s

#68 chore: resolve transitive dependencies on set-value and ansi-regex
  package.json
  yarn.lock
Labels: size/s
