Repository awslabs/fhir-works-on-aws-authz-smart, pull requests merged in 2021-08, with the labels that each got.

#51 chore(release): 2.1.1
  CHANGELOG.md
  package.json
Labels: documentation, size/xs

#50 feat: use fhirServiceBaseUrl from requests if present
  package.json
  src/smartHandler.test.ts
  src/smartHandler.ts
  yarn.lock
Labels: size/m

#52 chore(release): 2.2.0
  CHANGELOG.md
  package.json
Labels: size/xs

#53 fix: pass fhirServiceBaseUrl in bundle request auth
  package.json
  src/smartHandler.ts
  yarn.lock
Labels: size/s

#54 chore(release): 2.2.1
  CHANGELOG.md
  package.json
Labels: size/xs

#56 fix: group export permission update
  src/smartScopeHelper.test.ts
  src/smartScopeHelper.ts
Labels: size/s

#57 chore(release): 2.2.2
  CHANGELOG.md
  package.json
Labels: size/xs
