Repository awslabs/fhir-works-on-aws-authz-smart, pull requests merged in 2021-02, with the labels that each got.

#23 chore: add PR labeler
  .github/workflows/labeler.yml
Labels: size/s

#22 feat: make reference checking more restrictive and abid by FHIR
  .eslintrc.js
  .gitignore
  scripts/generateResourceReferenceMatrixFile.ts
  src/schema/fhirResourceReferencesMatrix.v3.0.1.json
  src/schema/fhirResourceReferencesMatrix.v4.0.1.json
  src/smartAuthorizationHelper.test.ts
  src/smartAuthorizationHelper.ts
  src/smartHandler.ts
  tsconfig.json
Labels: enhancement, size/xl

#24 feat: make smartHandler more configurable
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  THIRD-PARTY
  src/smartAuthorizationHelper.test.ts
  src/smartAuthorizationHelper.ts
  src/smartHandler.ts
Labels: documentation, enhancement, size/xl

#25 chore(release): 0.1.3
  CHANGELOG.md
  package.json
Labels: documentation, size/s

#26 chore: update ignore files
  .gitignore
  .npmignore
Labels: chore, size/xs

#27 chore(release): 1.0.0
  CHANGELOG.md
  package.json
Labels: documentation, size/xs
