Repository awslabs/fhir-works-on-aws-authz-smart, pull requests merged in 2021-07, with the labels that each got.

#43 feat: allow regex in SMARTConfig.expectedAudValue
  src/smartAuthorizationHelper.test.ts
  src/smartAuthorizationHelper.ts
  src/smartConfig.ts
Labels: size/s

#45 feat: use fhirServiceBaseUrl from requests if present
  src/smartHandler.test.ts
  src/smartHandler.ts
Labels: size/m

#44 feat: allow token introspection as an authz option
  src/smartAuthorizationHelper.test.ts
  src/smartAuthorizationHelper.ts
  src/smartConfig.ts
  src/smartHandler.test.ts
  src/smartHandler.ts
Labels: enhancement, size/m

#46 fix: support system scope
  src/smartAuthorizationHelper.ts
  src/smartHandler.test.ts
  src/smartHandler.ts
  src/smartScopeHelper.test.ts
Labels: bug, size/m
