Repository awslabs/fhir-works-on-aws-authz-smart, pull requests merged in 2021-05, with the labels that each got.

#35 refactor: add customized logger
  package.json
  scripts/generateResourceReferenceMatrixFile.ts
  src/loggerBuilder.ts
  src/smartAuthorizationHelper.ts
  src/smartHandler.ts
  yarn.lock
Labels: size/m

#36 chore(release): 1.0.1
  CHANGELOG.md
  package.json
Labels: size/xs

#34 chore: adding Github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/miscellaneous.md
Labels: size/s
