Repository awslabs/fhir-works-on-aws-authz-smart, pull requests merged in 2022-09, with the labels that each got.

#88 fix: only allow scopes to be returned iff it matches resourceType
  src/smartHandler.test.ts
  src/smartScopeHelper.test.ts
  src/smartScopeHelper.ts
Labels: bug, size/s

#89 docs: fix links
  README.md
Labels: documentation, size/xs

#91 chore(release): 3.1.2
  CHANGELOG.md
  package.json
Labels: size/xs, auto-release-pr

#92 fix: handle include/revInclude correctly
  src/smartAuthorizationHelper.test.ts
  src/smartAuthorizationHelper.ts
  src/smartHandler.test.ts
  src/smartHandler.ts
  src/smartScopeHelper.test.ts
  src/smartScopeHelper.ts
Labels: bug, size/m

#93 chore(release): 3.1.3
  CHANGELOG.md
  package.json
Labels: size/xs, auto-release-pr

#95 docs: Update README
  README.md
Labels: size/xs
